---
- name: Find kibana version
  command: docker exec -t kibana /usr/share/kibana/bin/kibana --version
  register: kibana_version
  changed_when: true
  when:
    - kibana_default_index is defined
    - kibana_default_indexes is defined
    - kibana_default_indexes['.kibana']['mappings']['doc']['properties']['config']['properties']['defaultIndex'] is not defined

- set_fact:
    kibana_version: "{{ kibana_version.stdout }}"
  connection: local
  when:
    - kibana_default_index is defined
    - kibana_default_indexes is defined
    - kibana_default_indexes['.kibana']['mappings']['doc']['properties']['config']['properties']['defaultIndex'] is not defined

# NOTE(kiennt): Start from 6.x version, creating Kibana index manually is unnecessary.
- name: Kibana without xpack
  block:
  - name: Wait for kibana port
    wait_for:
      host: "{{ kolla_internal_vip_address }}"
      port: "{{ kibana_server_port }}"

  - name: Register the kibana index in elasticsearch
    uri:
      url: "{{ internal_protocol }}://{{ kolla_internal_vip_address }}:{{ elasticsearch_port }}/.kibana"
      method: PUT
      body: "{{ kibana_default_index_options | to_json }}"
      body_format: json
      status_code: 200, 201, 400
    register: result
    failed_when:
      # If the index already exists, Elasticsearch will respond with a 400 error.
      - result.status == 400
      # Format: {"json": {"error": {"type": "resource_already_exists_exception"}}}
      - result.get('json', {}).get('error', {}).get('type') != 'resource_already_exists_exception'

  - name: Wait for kibana to register in elasticsearch
    uri:
      url: "{{ internal_protocol }}://{{ kolla_internal_vip_address }}:{{ elasticsearch_port }}/.kibana"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 20
    delay: 2

  - name: Make index to defaultIndex
    uri:
      url: "{{ internal_protocol }}://{{ kolla_internal_vip_address }}:{{ kibana_server_port }}/api/kibana/settings/defaultIndex"
      method: POST
      body:
        value: "{{ kibana_default_index_pattern }}"
      body_format: json
      user: "{{ kibana_user }}"
      password: "{{ kibana_password }}"
      headers:
        kbn-xsrf: true
    when:
      - kibana_default_index is defined
      - kibana_default_indexes is defined
      - kibana_default_indexes['.kibana']['mappings']['doc']['properties']['config']['properties']['defaultIndex'] is not defined
  run_once: true
  when:
    - kibana_version | string is version('6.0.0', '<')
    - not es_enable_xpack | bool
