---
- name: Restart elasticsearch container
  vars:
    service_name: "elasticsearch"
    service: "{{ elasticsearch_services[service_name] }}"
    config_json: "{{ elasticsearch_config_jsons.results|selectattr('item.key', 'equalto', service_name)|first }}"
    elasticsearch_conf: "{{ elasticsearch_confs.results|selectattr('item.key', 'equalto', service_name)|first }}"
    elasticsearch_jvm_option: "{{ elasticsearch_jvm_opts.results|selectattr('item.key', 'equalto', service_name)|first }}"
    elasticsearch_container: "{{ check_elasticsearch_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
    es_cert_creation: "{{ es_create_cert is defined and es_create_cert.changed | bool }}"
    es_bootstrap_password_creation: "{{ es_create_bootstrap_password is defined and es_create_bootstrap_password.changed | bool }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    environment: "{{ service.environment }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
  when:
    - kolla_action != "config"
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - config_json.changed | bool
      or elasticsearch_conf.changed | bool
      or elasticsearch_container.changed | bool
      or elasticsearch_jvm_option.changed | bool
      or es_cert_creation | bool
      or es_bootstrap_password_creation | bool
