---
- hosts: controller_new
  gather_facts: false
  become: true
  tasks:
  - name: Include iptables
    include_tasks: iptables.yml

  - name: Include play config and update repo
    include_tasks: config_repo.yml

  - name: Include play install packages
    include_tasks: install_package.yml

  - name: Include play tuning sysctl
    include_tasks: sysctl_tuning.yml

  - name: Include play limit RAM for rsyslog
    include_tasks: rsyslog.yml
