---
- hosts: test
  gather_facts: false
  become: True
  tasks:
  - name: copy multipath config file 
    copy:
      src: multipath-dell-and-ibm.conf
      dest: /etc/kolla/multipathd/multipath.conf

  - name: Install device-mapper-multipath package
    yum:
      name: "device-mapper-multipath"
      state: latest

  - name: rebuild initramfs
    shell: "/sbin/dracut -v --force --add multipath --include /etc/kolla/multipathd/multipath.conf"
    register: initramfs

  - name: Remove device-mapper-multipath package
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
        - device-mapper-multipath
        - device-mapper-multipath-libs

  - debug:
      msg: "{{ initramfs.stderr_lines }}"
