---
- hosts: test
  gather_facts: false
  become: true
  tasks:
  - name: Get scsi of root disk
    shell: ls -la /dev/disk/by-id/ | grep scsi | grep $(eval $(lsblk -oMOUNTPOINT,PKNAME -P  | grep 'MOUNTPOINT="/boot"'); echo $PKNAME | sed 's/[0-9]*$//')$ | awk ' { print $9 }'
    register: scsi_root
  - name: scsi_root variable
    debug:
      msg: "{{ scsi_root.stdout }}"
  - name: Backup and copy lvmlocal.conf
    template:
      src: lvmlocal.j2
      dest: /etc/lvm/lvmlocal.conf
      backup: yes
  - name: copy lvmlocal.conf to containers
    shell: docker cp /etc/lvm/lvmlocal.conf {{ item }}:/etc/lvm/lvmlocal.conf
    with_items:
      - openvswitch_vswitchd
      - openvswitch_db
      - nova_libvirt
      - multipathd
      - prometheus_cadvisor
      - chrony
