---
- hosts: osd
  gather_facts: false
  become: True
  tasks:
  - name: Check SLOW_OPS
    shell: for i in $(ls -la /var/lib/ceph/osd/ | awk {'print $9'} | cut -d'-' -f2); do ceph daemon osd.$i dump_historic_ops; done;

  - name: Retrieve diagnostic messages,
    shell: dmesg | grep scsi

  - name: Origin of slow requests
    shell: for i in $(ls -la /var/lib/ceph/osd/ | awk {'print $9'} | cut -d'-' -f2); do ceph daemon osd.$i dump_ops_in_flight; done;

