---
- hosts: compute_new
  gather_facts: true
  tasks:
    - name: Backup network scripts
      shell: cp -r /etc/sysconfig/network-scripts /root/network-scripts.bak

    - name: Clean networks configuration
      shell: rm -f /etc/sysconfig/network-scripts/ifcfg-*

    - name: Generate bonds mode 4
      template: src=bond.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ item }}
      with_items: "{{ bonds.replace(' ', '').split(',') }}"
      notify:
      - Restart network

    - name: Generate external interface
      template: src=external_interface.j2 dest="/etc/sysconfig/network-scripts/ifcfg-{{ external_interface }}.cfg"
      notify:
      - Restart network

    - name: Generate internal interface
      template: src=internal_interface.j2 dest="/etc/sysconfig/network-scripts/ifcfg-{{ internal_interface }}.cfg"
      notify:
      - Restart network

    - name: Generate other interface
      template: src=other_interface.j2 dest="/etc/sysconfig/network-scripts/ifcfg-{{ item }}.cfg"
      with_items: "{{ other_interface.replace(' ', '').split(',') }}"
      when: other_interface is defined
      notify:
      - Restart network

    - name: Collect bonds slave
      shell: cat /proc/net/bonding/{{ item }} | grep "Slave Interface" | awk '{print $3}'
      with_items: "{{ bonds.replace(' ', '').split(',') }}"
      register: bonds_slave

    - name: Generate bonds slave
      template: src=bond-slave.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ item.1 }}
      with_subelements:
        - "{{ bonds_slave.results }}"
        - stdout_lines
      notify:
      - Restart network

    - name: Add route
      template: src=route.j2 dest=/etc/sysconfig/network-scripts/route-{{ item.dev }}
      with_items : "{{ add_route }}"
      when: add_route is defined
      notify:
      - Restart network

  handlers:
    - name: Restart network
      service:
        name: network
        state: restarted

